# Generated from create-stratocastR.Rmd: do not edit by hand

#' Convert a plate dataset to a tsibble; detect outlier timepoints in each well
#'
#' @param data (dataframe) Plate data data.frame, as generated by read_platedata()
#' @param interval (numeric) Length of time step in minutes, as read by get_interval_min()
#' @param iter (numeric) Number of outlier-detection iterations for `forecast::tsoutliers()` to run.
#'   Defaults to 1.
#' @param incol (character) Column to analyze for outliers.  To examine raw absorbances, e.g., in
#'   blank wells before aggregation, use "absorbance"; to examine background-subtracted absorbances,
#'   e.g., in test wells, use "abs.corr"; to examine air temperature, use "airtemp.C".
#' @return A tsibble that adds two new columns to data:
#'   - a per-well per-timestep outlier detection result from `forecast::tsoutliers()`; depending on
#'     the value of `incol`, the column may be `is.outlier.temp` or `is.outlier.abs`
#'   - `n.out.bgtype`, a per-timestep count of the number of wells in the background type flagged as
#'     outliers
#' @export
detect_outliers <- function(data, interval, iter = 1,
                            incol = c("absorbance", "abs.corr", "airtemp.C")) {
    outcol <- ifelse(incol == "airtemp.C", "is.outlier.temp", "is.outlier.abs")
    data <- tsibble::as_tsibble(data, key = well, index = timestamp)
    outs <- {data %>%
                 split(data$well) %>%
                 purrr::map(\(tsib) data.frame(well = unique(tsib$well),
                                               outstep =
                                                   forecast::tsoutliers(tsib[[incol]],
                                                                        iterate = iter)$index,
                                               is.outlier = TRUE)) %>%
                 dplyr::bind_rows() %>%
                 dplyr::mutate(duration.min = interval * outstep) %>%
                 dplyr::select(-outstep)}
    data <- {dplyr::left_join(data, outs) %>%
                 dplyr::mutate(is.outlier = tidyr::replace_na(is.outlier, FALSE)) %>%
                 dplyr::rename_with(~outcol, is.outlier)}
    if (incol != "airtemp.C") {
        problem.steps <- {data %>%
                              as.data.frame() %>%
                              dplyr::group_by(duration.min, bgtype) %>%
                              dplyr::summarise(n.out.bgtype = sum(is.outlier.abs))}
        data <- dplyr::left_join(data, problem.steps)
    }
    return(data)
}
